targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|schema_builder:
        enabled: true
        options:
          schema: flutter_github_test|lib/core/graph_ql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
      gql_build|data_builder:
        enabled: true
        options:
          schema: flutter_github_test|lib/core/graph_ql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
      gql_build|var_builder:
        enabled: true
        options:
          schema: flutter_github_test|lib/core/graph_ql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: flutter_github_test|lib/core/graph_ql/schema.graphql
          custom_serializers:
            - import: package:flutter_github_test/utils/date_time_serializer.dart
              name: DateTimeSerializer
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: flutter_github_test|lib/core/graph_ql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
