name: flutter_github_test
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  ferry: ^0.10.2 #graph ql
  ferry_flutter: ^0.5.2
  filesize: ^2.0.1
  fimber: ^0.6.1
  fluro: ^2.0.3
  flutter_markdown: ^0.6.2
  flutter_svg: ^0.22.0
  flutter_highlight: ^0.7.0
  flutter_vector_icons: ^1.0.0
  github: ^8.1.0
  gql_http_link: ^0.4.0-nullsafety.1
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  nanoid: ^1.0.0
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  tuple: ^2.0.0
  uni_links: ^0.5.1
  universal_io: ^2.0.4
  uri: ^1.0.0
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4
  equatable: ^2.0.3
  dartz: ^0.10.0-nullsafety.2

  # Dart data class
  json_serializable: ^4.1.3
  freezed_annotation: ^0.14.2

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.4.1

  # State management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1

  internet_connection_checker: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Codegen
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  build_runner: ^2.0.4
  ferry_generator: ^0.4.2

  # Testing
  #bloc_test: ^7.1.0
  #mockito: ^4.1.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
flutter_intl:
  enabled: true